### ISSUE TITLE
Scaling (Polarization)

### ISSUE THREAD

**Issue by limjoowon** [gevero/py_gmm#13]
Hello,

I am trying to do some simulations using the software.
The examples are very clear to follow. It is very helpful.

I have a question. I am using a x-polarized incident wave (gamma = 0).

In the local filed calculation part, it saves out[3], which I think it is the absolute value of Electric field, |E|.
If I want to access **the complex electric field (polarized in x)** itself, which value should I look for?
I think it is out[0] (Am I right? If not, please, let me know).

But when I calculate the absolute value of out[0] using real and imaginary parts, it is much less than 1 (about 0.5). As long as I use the incident field (which is already polarized in x and the amplitude is 1), the absolute value of resulting x-polarized field should be around 1. 

Could you give me some comments?

Best,

JooWon.

**Comment by gevero** [comment]
Hi

`out[0]` is indeed the x component of the complex electric field. The field returned by subroutine `exyz` is either the scattered field (first flag ='no') or the scattered plus incident field (first flag ='yes'), so I do no see why it should be identically 1, since the scattered field is included. If you anyway make a check for a very weakly scattering sphere very far away from the sphere, I would expect to find the correct amplitude for the incident field.

best

Giovanni

**Comment by limjoowon** [comment]
Hi,

So out[0] is the x-polarized output.
Yes, I measure the total electric field (with the incident field), and observed at a point far away from a weekly scattering sample. Still, I get smaller values.
As long as out[0] is the x-polarized output, I think I can figure out by try-and-error.

Thanks.

Best,

JooWon.

**Comment by gevero** [comment]
I shall look into the code to see if something is wrong, but I tested against numerous examples, and always found perfect agreement (see figure two [of this paper](http://pubs.acs.org/doi/abs/10.1021/acs.jpcc.6b08802) for instance). Anyway, you can see the definition of the incident field [here](https://github.com/gevero/py_gmm/blob/c0021dc4c2f3a132b66b293729c7bdeb713e6305/py_gmm/gmm_f2py_module.f90#L648), then multiplied by the phase shift [here](https://github.com/gevero/py_gmm/blob/c0021dc4c2f3a132b66b293729c7bdeb713e6305/py_gmm/gmm_f2py_module.f90#L795). So i guess that everything should be ok, but bugs are always possible.

Best

Giovanni

**Comment by limjoowon** [comment]
Thank you for your further information!

If n = a + ib, then eps consists of real part of (a+ib)^2 and imag part of (a+ib)^2.
Is it right?

Best,

JooWon.

**Comment by gevero** [comment]
re_eps=real{(a+ib)^2}, im_eps=imag{(a+ib)^2}

**Comment by yx14** [comment]
> I shall look into the code to see if something is wrong, but I tested against numerous examples, and always found perfect agreement (see figure two [of this paper](http://pubs.acs.org/doi/abs/10.1021/acs.jpcc.6b08802) for instance). Anyway, you can see the definition of the incident field [here](https://github.com/gevero/py_gmm/blob/c0021dc4c2f3a132b66b293729c7bdeb713e6305/py_gmm/gmm_f2py_module.f90#L648), then multiplied by the phase shift [here](https://github.com/gevero/py_gmm/blob/c0021dc4c2f3a132b66b293729c7bdeb713e6305/py_gmm/gmm_f2py_module.f90#L795). So i guess that everything should be ok, but bugs are always possible.
> 
> Best
> 
> Giovanni

Hi, 

I'm trying to create a plane wave with arbitrary direction and polarization, and was looking at previous issues about the euler angles. It seems that v_kinc and v_Einc aren't generally perpendicular. (For example, [alpha, beta, gamma] = [np.pi/5, np.pi/3, np.pi/2] results in a dot product of t v_kinc*v_Einc = -0.82.) Is v_Einc the polarization vector, or something else?

Thank you, 

Julia

**Comment by gevero** [comment]
I will look into it and get back to you

**Comment by gevero** [comment]
Hi Julia

Thanks for pointing out this problem. I actually found that the Ey component of the incident field was wrong:
```
v_Einc(2)=SIN(alpha0)*COS(beta0)*COS(gamma0)-COS(alpha0)*SIN(gamma0)
```
instead of
```
v_Einc(2)=SIN(alpha0)*COS(beta0)*COS(gamma0)+COS(alpha0)*SIN(gamma0)
```
This bug only affected the plotting of the local field when the incident field was included. All the other calculations are correct because the use directly the spherical wave expansions for the incident field. I myself never experienced it because I always use z-propagating waves.

Thanks again for pointing out this bug.

Best

Giovanni

**Comment by yx14** [comment]
Thanks so much for the clarification!
