### ISSUE TITLE
Maximum number of 

### ISSUE THREAD

**Issue by limjoowon** [gevero/py_gmm#15]
Hello,

Thank you for the nice software.
I am now simulating the code.
I would like to increase the value of "n_stop (# maximum multipolar expansion order)" to be 100 or more.

When I do that, I get NaN.
In the program, it is not allowed to increase over a certain value?

Best,

JooWon.

**Comment by gevero** [comment]
Hi

Yes, there is a maximum number, even if it depends on the simulation you are runnining. The problems are several:

1. You are computing spherical bessel and hankel functions of very high order, and for n_stop=100 they will surely overflow double precision computation. I guess the `NaN` is coming from there.
2. The required memory is going to scale quadratically with n_stop, so a computation with n=100 would require a lot of memory
3. With n_stop = 100, you would also require a lot of time, because you need to calculate a lot of vector translation coefficients.

In practice I never run a calculation with n_stop>40. Why do you need so many multipoles? What kind of system are you modeling? A system with a small gap where the multipoles are needed to model the quickly varying field, or simply a system of big spheres?

Best

Giovanni

**Comment by limjoowon** [comment]
Hello Giovanni,

Thank you for your quick answer.
I am trying to simulate 2 spheres which are pretty large (about 5 um in diameter).

Best,

JooWon

**Comment by gevero** [comment]
and how large is the gap between the spheres?

**Comment by limjoowon** [comment]
It is flexible.
What I would like to try is two spheres which overlap in the z-axis.
Diameter of each is about 5 um.
The distance from center to center is about 10 um.

**Comment by gevero** [comment]
I see! In my opinion you could try and see what happens with n_stop=30 or n_stop=35. It is not too far away from Wiscombe criterion and the calculation might converge!

**Comment by limjoowon** [comment]
Thank you for your comments.

Joowon
