### ISSUE TITLE
Is it possible to calculate the near field with H perpendicular to E and k?

### ISSUE THREAD

**Issue by einarmiger** [gevero/py_gmm#8]
Hi Gevero,
i would like to calculate the near field of spheres with a magnetic field perpendicular to E and k.
Would that be possible with your code? 
From looking at your code i am not sure if it is possible because i didn't find anything about magnetic fields, but i am not that experienced in Fortran. 
Regards Thomas

**Comment by gevero** [comment]
Hi Thomas

I am not sure if I understand your question. If you want to illuminate your sphere with a plane wave, which  by definition is a transverse wave, where E,H and k are perpendicular to each other, you are all set. While in the input file you set only polarization and incident direction with E and k, H is automatically taken into account, since it is, by definition of plane wave, perpendicular to the former two. I hope I answered your question, and if you have further doubts feel free to ask away.

Best

Giovanni

**Comment by einarmiger** [comment]
Thanks Giovanni, yes, thats exactly what i meant. Regards Thomas
