### ISSUE TITLE
Is it possible to calculate efficiencies of spherical nano-shells?

### ISSUE THREAD

**Issue by yael1991** [gevero/py_gmm#9]
Hi,
I have a question concerning core-shell nanoparticles.
Does this code calculate efficiencies of core-shell spherical nanoparticles?
Thanks,
Yael

**Comment by gevero** [comment]
Hi

The answer is... it depends! Actually, there is a module of the code that work for symmetric and asymmetric  core-shell nanoparticles, but only isolated ones ([see this paper](http://pubs.acs.org/doi/abs/10.1021/jp306025b)). The problem is that I never released it on github, because i never had the time to polish it. Do you need one or many interacting core shell nanoparticles?

Best

Giovanni

**Comment by yael1991** [comment]
Hi,
Thank you for your fast answer.
I am trying to model core-satellite system with a core-shell particle as core particle.
Best,
Yael

**Comment by gevero** [comment]
Well

Then it's a thing that for the moment cannot be done. It should not be hard to implement, but unfortunately I don't have the time now. I shall leave this issue open so, If I update the code to work with clusters of core-shell particles, you'll be the first to know it.

Best

Giovanni

**Comment by yael1991** [comment]
Ok, thanks so much anyway.
Very nice work you have here.
Best
Yael
